name: Continuous Deployment to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key for EC2 access
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to EC2 using Docker Swarm
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            # Navigate to the target directory
            cd /home/ubuntu/fastlog-sptech

            # Pull the latest changes
            git pull origin main

            # Build Docker image
            docker build -t react-frontend:latest .

            docker service ls -q | xargs -r docker service rm

            docker network create --driver overlay fastlog || true

            # Deploy using Docker Swarm
            docker service create --name frontend --replicas 3 -p 80:80 --network fastlog react-frontend:latest
          EOF