name: Continuous Deployment to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key for EC2 access
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build -t react-frontend:latest .

      - name: Deploy to EC2 using Docker Swarm
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            # Navigate to the target directory
            cd /fastlog-sptech || git clone https://github.com/your-username/your-repo.git /fastlog-sptech
            cd /fastlog-sptech  # Make sure we are in the project directory

            # Pull the latest changes
            git pull origin main

            # Build Docker image
            docker build -t react-frontend:latest .

            # Deploy using Docker Swarm
            docker service create --name frontend1 --replicas 1 -p 80:80 react-frontend:latest
            docker service create --name frontend2 --replicas 1 -p 80:80 react-frontend:latest
            docker service create --name frontend3 --replicas 1 -p 80:80 react-frontend:latest
          EOF
